version: '3'
services:
  # DBT
  dbt:
    image: article1dataops/dbt:latest
    volumes:
      - .:/usr/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      my_network:
        ipv4_address: 172.20.0.10

  # Postgres database
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_app
    ports:
      - "5432:5432"
    networks:
      my_network:
        ipv4_address: 172.20.0.20

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
